create table languages
(
    code      char(2)      not null
        primary key,
    flag_icon varchar(255),
    name      varchar(255) not null
);

alter table languages
    owner to postgres;

create table lessons
(
    id          integer generated by default as identity
        primary key,
    description varchar(255),
    title       varchar(255) not null
);

alter table lessons
    owner to postgres;

create table exercises
(
    id        integer generated by default as identity
        primary key,
    content   jsonb        not null,
    "order"   integer      not null,
    type      varchar(255) not null,
    xp_reward integer,
    lesson_id integer      not null
        constraint fkes9e0n86cjfb0l6349clxvxc1
            references lessons
);

alter table exercises
    owner to postgres;


